keyMirror = require "react/lib/keyMirror"

module.exports = keyMirror
  ADD_REFINER: "ADD_REFINER"
  REMOVE_REFINER: "REMOVE_REFINER"
  CLEAR_REFINER: "CLEAR_REFINER"
  SET_FILTER: "SET_FILTER"
  ADD_TO_SHOPPINGBAG: "ADD_TO_SHOPPINGBAG"
  SELECT_QUANTITY: "SELECT_QUANTITY"