module.exports =
	init: ->
		localStorage.clear()
		localStorage.setItem "products", JSON.stringify [
				id: "00000001"
				sku: "123123"
				name: "Château Gruaud-Larose Larose de Gruaud Saint Julien 2006 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "DFS Selects: Wine"
				currency: "S$"
				price: "100.00"
				country: "france"
				grape_varietal: "Merlot"
				region: "Bordeaux"
				shop_recommended: "true"
				inventory: 11
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000002"
				sku: "235354"
				name: "Babich Irongate Cabernet Merlot Franc 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Babich Wines Ltd"
				price: "200"
				country: "Argentina"
				grape_varietal: "Sangiovese"
				region: "Burgundy"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000003"
				name: "Mud House Marlborough Pinot Gris 2013 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Mud HOurs"
				price: "100.00"
				country: "spain"
				grape_varietal: "Cabearnet Sauvignon"
				region: "Central Otago"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000004"
				name: "Zinfandelic 2012 Sierra Foothills Old Vine Zinfandel 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Zinfandelic"
				price: "100.00"
				country: "south africa"
				grape_varietal: "Shiraz"
				region: "Champagne"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,			
				id: "00000005"
				name: "Bottega Il Vino dell’Amore Petalo Moscato 0.2L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Bottega"
				price: "100.00"
				country: "Germany"
				grape_varietal: "riesling"
				region: "graves"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000006"
				name: "Wine Spots 2011 Napa Valley Cabernet Sauvignon 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Wine Spots"
				price: "100.00"
				country: "chile"
				grape_varietal: "pinot noir"
				region: "Bordeaux"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000007"
				name: "Frescobaldi Mormoreto 2010 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Frescobaldi"
				price: "100.00"
				country: "france"
				grape_varietal: "Merlot"
				region: "South Australia"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000008"
				name: "Tommasi Monte Croce Passito Bianco IGT 2010 0.375L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Tommasi"
				price: "100.00"
				country: "france"
				grape_varietal: "Merlot"
				region: "St. Julien"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000009"
				name: "Yalumba Y Series South Australia Sangiovese Rose 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Yalumba"
				price: "100.00"
				country: "canada"
				grape_varietal: "Merlot"
				region: "Rhone Valley"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000010"
				name: "Silver Oak Napa Valley Cabernet Sauvignon 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Silver Oak Cellars"
				price: "100.00"
				country: "united states"
				grape_varietal: "Sauvignon Blanc"
				region: "Pessac Leognan"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."
			,
				id: "00000011"
				name: "Frescobaldi Nipozzano Riserva 0.75L"
				image: "http://placehold.it/200"
				category: "wine"
				brand: "Frescobaldi"
				price: "100.00"
				country: "england"
				grape_varietal: "Bordeaux Red Blend"
				region: "Tuscany"
				shop_recommended: "true"
				currency: "S$"
				inventory: 12	
				description: "Integer quis magna purus. Duis ut velit magna. In hac habitasse platea dictumst. Nullam ac blandit nisl. Cras eget mi erat. Nunc congue dolor felis, nec cursus elit rutrum eu."			
		]